Fix release script 10.31.0
anthem could not be started in pre because of a new field added on
res_partner (so cannot initialize res_users):

psycopg2.ProgrammingError: column res_partner.show_deliveryslip_cnk does not exist
LINE 1: ...company","res_partner"."write_uid" as "write_uid","res_partn...